### ISSUE TITLE
Does not load svg in modal box in IE11

### ISSUE THREAD

**Issue by mcmimik** [Keyamoon/svgxuse#10] opened 2016-02-03 10:40 UTC
Hi! I have a modal dialog that is hidden by default and is visible on click.

In IE11 the `use` element is visible in the usual layout but it is not visible inside the modal (maybe because modal is hidden on page load) when modal is opened by click.

Chrome and others copes well with modal box.

**Comment by Keyamoon** [comment] 2016-02-03 14:30
I can't reproduce this issue. Can you provide a reduced test case? [Here's what I've came up with](http://codepen.io/anon/pen/MKqajP) but it works fine in IE11. I suspect your CSS for hiding/showing the modal is different.

**Comment by mcmimik** [comment] 2016-02-04 11:39
Yes, here's my test case: [http://run.plnkr.co/plunks/1Z4bao/](http://run.plnkr.co/plunks/1Z4bao/).

**Comment by Keyamoon** [comment] 2016-02-04 15:10
Thank you for the test case. :+1: 

Please try again now. It should be fixed.

**Comment by mcmimik** [comment] 2016-02-04 18:14
Thank you! It works perfect 👌

**Closed as completed** 2016-02-04 18:15 UTC
